swagger: "2.0"
info:
  title: ODM2 REST API
  version: v1
  contact: 
    email: landungs@uw.edu
    name: Landung Setiawan
  description: This is a development version for ODM2 REST API
host: 127.0.0.1:8000
basePath: /v1
tags:
  - name: affiliations
    description: Affiliations in database
  - name: people
    description: People in database
  - name: results
    description: Results in database
  - name: samplingfeatures
    description: Sampling Features in database
  - name: datasets
    description: Data Sets in database
  - name: methods
    description: Methods in database
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
  - application/yaml
  - text/csv
paths:
  /affiliations:
    get:
      tags:
      - affiliations
      operationId: getAffiliations
      summary: ODM2 affiliations retrieval by Affiliation ID(s)
      parameters:
        - name: affiliationID
          in: query
          description: Affiliation ID(s)
          required: false
          type: string 
        - name: firstName
          in: query
          description: Person First Name
          required: false
          type: string
        - name: lastName
          in: query
          description: Person Last Name
          required: false
          type: string
        - name: organizationCode
          in: query
          description: Organization Code
          required: false
          type: string 
      responses:
        "200":
          description: 200 Response
  /people/:
    get:
      tags:
      - people
      operationId: getPeopleVersion1
      summary: All ODM2 people retrieval.
      responses:
        "200":
          description: 200 Response
  /people/peopleID/{peopleID}/:
    get:
      tags:
      - people
      operationId: getPeopleByPeopleID
      summary: ODM2 people retrieval by People ID(s)
      parameters:
        - name: peopleID
          in: path
          description: People ID(s)
          required: true
          type: string
      responses:
        "200":
          description: 200 Response
  /people/firstName/{firstName}/:
    get:
      tags:
      - people
      operationId: getPeopleByFirstName
      summary: ODM2 people retrieval by First Name
      parameters:
        - name: firstName
          in: path
          description: Person First Name
          required: true
          type: string
        - name: lastName
          in: query
          description: Person Last Name
          required: false
          type: string
      responses:
        "200":
          description: 200 Response
  /people/lastName/{lastName}/:
    get:
      tags:
      - people
      operationId: getPeopleByLastName
      summary: ODM2 people retrieval by Last Name
      parameters:
        - name: lastName
          in: path
          description: Person Last Name
          required: true
          type: string 
      responses:
        "200":
          description: 200 Response
  /results:
    get:
      tags:
      - results
      operationId: getResultsVersion1
      summary: All ODM2 results retrieval.
      parameters:
        - name: resultID
          in: query
          description: Result ID(s)
          required: false
          type: string
        - name: resultUUID
          in: query
          description: Result UUID(s)
          required: false
          type: string
        - name: resultType
          in: query
          description: Result Type (Name). <br>
                       See all available Result Types [here](http://vocabulary.odm2.org/resulttype/).
          required: false
          type: integer
        - name: actionID
          in: query
          description: Action ID
          required: false
          type: integer
        - name: samplingFeatureID
          in: query
          description: Sampling Feature ID
          required: false
          type: integer
        - name: siteID
          in: query
          description: Site ID
          required: false
          type: integer
        - name: variableID
          in: query
          description: Variable ID
          required: false
          type: integer
        - name: simulationID
          in: query
          description: Simulation ID
          required: false
          type: integer
      responses:
        "200":
          description: 200 Response
  /resultvalues/resultID/{resultID}/:
      get:
        tags:
        - results
        operationId: getResultValuesByResultID
        summary: ODM2 result values retrieval by Result ID(s)
        parameters:
          - name: resultID
            in: path
            description: Result ID(s)
            required: true
            type: integer
          - name: beginDate
            in: query
            description: Begin Date 'yyyy-mm-dd hh:mm:ss'
            required: false
            type: string
          - name: endDate
            in: query
            description: End Date 'yyyy-mm-dd hh:mm:ss'
            required: false
            type: string
        responses:
          "200":
            description: 200 Response
  /samplingfeatures/:
    get:
      tags:
      - samplingfeatures
      operationId: getSamplingFeatures
      summary: All ODM2 samplingfeatures retrieval.
      parameters:
        - name: results
          in: query
          description: Get Sampling Features that has Results
          required: false
          type: boolean
      produces:
      - application/json
      - application/yaml
      responses:
        "200":
          description: 200 Response
  /samplingfeatures/samplingFeatureID/{samplingFeatureID}/:
    get:
      tags:
      - samplingfeatures
      operationId: getSamplingFeatureBySamplingFeatureID
      summary: ODM2 samplingfeatures retrieval by Sampling Feature ID(s)
      parameters:
        - name: samplingFeatureID
          in: path
          description: Sampling Feature ID(s)
          required: true
          type: string 
        - name: results
          in: query
          description: Get Sampling Features that has Results
          required: false
          type: boolean
      responses:
        "200":
          description: 200 Response
  /samplingfeatures/samplingFeatureCode/{samplingFeatureCode}/:
    get:
      tags:
      - samplingfeatures
      operationId: getSamplingFeatureBySamplingFeatureCode
      summary: ODM2 samplingfeatures retrieval by Sampling Feature Code(s)
      parameters:
        - name: samplingFeatureCode
          in: path
          description: Sampling Feature Code(s)
          required: true
          type: string 
        - name: results
          in: query
          description: Get Sampling Features that has Results
          required: false
          type: boolean
      responses:
        "200":
          description: 200 Response
  /samplingfeatures/samplingFeatureType/{samplingFeatureType}/:
    get:
      tags:
      - samplingfeatures
      operationId: getSamplingFeatureBySamplingFeatureType
      summary: ODM2 samplingfeatures retrieval by Sampling Feature Type
      externalDocs: 
          description: "See all available Sampling Feature Types"
          url: "http://vocabulary.odm2.org/samplingfeaturetype/"
      parameters:
        - name: samplingFeatureType
          in: path
          description: Sampling Feature Type(s)
          required: true
          type: string 
        - name: results
          in: query
          description: Get Sampling Features that has Results
          required: false
          type: boolean
      responses:
        "200":
          description: 200 Response
  /datasets/:
    get:
      tags:
      - datasets
      operationId: getDataSets
      summary: All ODM2 datasets retrieval.
      produces:
      - application/json
      - application/yaml
      responses:
        "200":
          description: 200 Response
  /datasets/datasetUUID/{datasetUUID}/:
    get:
      tags:
      - datasets
      operationId: getDataSetsByDataSetUUID
      summary: ODM2 datasets retrieval by Data Set UUID(s)
      parameters:
        - name: datasetUUID
          in: path
          description: Data Set UUID(s)
          required: true
          type: string
      responses:
        "200":
          description: 200 Response
  /datasets/datasetCode/{datasetCode}/:
    get:
      tags:
      - datasets
      operationId: getDataSetsByDataSetCode
      summary: ODM2 datasets retrieval by Data Set Code(s)
      parameters:
        - name: datasetCode
          in: path
          description: Data Set Code(s)
          required: true
          type: string
      responses:
        "200":
          description: 200 Response
  /methods/:
    get:
      tags:
      - methods
      operationId: getMethods
      summary: All ODM2 methods retrieval
      produces:
      - application/json
      - application/yaml
      responses:
        "200":
          description: 200 Response
  /methods/methodCode/{methodCode}/:
    get:
      tags:
      - methods
      operationId: getMethodsByMethodCode
      summary: ODM2 methods retrieval by Method Code(s)
      parameters:
        - name: methodCode
          in: path
          description: Method Code(s)
          required: true
          type: string
      responses:
        "200":
          description: 200 Response
  /methods/methodID/{methodID}/:
    get:
      tags:
      - methods
      operationId: getMethodsByMethodID
      summary: ODM2 methods retrieval by Method ID(s)
      parameters:
        - name: methodID
          in: path
          description: Method ID(s)
          required: true
          type: string
      responses:
        "200":
          description: 200 Response
  /methods/methodType/{methodType}/:
    get:
      tags:
      - methods
      operationId: getMethodsByMethodType
      summary: ODM2 methods retrieval by Method Type(s)
      parameters:
        - name: methodType
          in: path
          description: Method Type
          required: true
          type: string
      responses:
        "200":
          description: 200 Response